# Triggers
trigger: none
pr: none

# Parameters
parameters:
  - name: releaseVersion
    displayName: Release Version
    type: string

# Stages
stages:
  - stage: publish_artifacts
    displayName: Publish artifacts for ${{ parameters.releaseVersion }}
    condition: startsWith(variables['build.sourceBranch'], 'refs/heads/release-')
    jobs:
      - template: 'templates/steps/release_artifacts.yaml'
        parameters:
          artifactSource: 'current'
          artifactProject: 'strimzi'
          artifactPipeline: ''
          artifactRunVersion: ''
          artifactRunId: ''
          releaseVersion: '${{ parameters.releaseVersion }}'