name: Build

on:
  push:
    branches:
      - "main"
      - "release-*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

# Declare default permissions as read only
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-kafka-kubernetes-config-provider:
    name: Build Kafka Kubernetes Config Provider
    strategy:
      matrix:
        java:
          - version: "11"
            mainBuild: false
          - version: "17"
            mainBuild: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java and Maven
        uses: strimzi/github-actions/.github/actions/dependencies/setup-java@v1
        with:
          javaVersion: ${{ matrix.java.version }}

      - name: Setup Kind cluster
        uses: strimzi/github-actions/.github/actions/dependencies/setup-kind@v1
        with:
          controlNodes: 1
          workerNodes: 1
          kindVersion: 0.31.0
        env:
          KIND_NODE_IMAGE: "latest"

      # ITs requires to have set default namespace in kubeconfig which is not by default with Kind
      - name: Set default namespace
        shell: bash
        run: kubectl config set-context --current --namespace=default

      - name: Build binaries using build-binaries action
        uses: strimzi/github-actions/.github/actions/build/build-binaries@v1
        with:
          mainJavaBuild: ${{ matrix.java.mainBuild }}
          artifactSuffix: "kafka-kubernetes-config-provider"
          clusterOperatorBuild: "false"

  deploy-java:
    name: Deploy Java artifacts
    needs:
      - build-kafka-kubernetes-config-provider
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java and Maven
        uses: strimzi/github-actions/.github/actions/dependencies/setup-java@v1
        with:
          javaVersion: "17"

      - name: Deploy to Maven Central
        uses: strimzi/github-actions/.github/actions/build/deploy-java@v1
        with:
          modules: "./"
          gpgPassphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpgSigningKey: ${{ secrets.GPG_SIGNING_KEY }}
          centralUsername: ${{ secrets.CENTRAL_USERNAME }}
          centralPassword: ${{ secrets.CENTRAL_PASSWORD }}