name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version (e.g., 1.5.0 for GA or 1.5.0-rc1 for RC)'
        required: true
        type: string

# Declare default permissions as read only
permissions:
  contents: read

jobs:
  prepare-release-artifacts:
    name: Prepare Release Artifacts
    if: ${{ startsWith(github.ref, 'refs/heads/release-') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Java and Maven
        uses: strimzi/github-actions/.github/actions/dependencies/setup-java@52b17c19f3687e37b47c9c64696b96f28f53625b # v2.3
        with:
          javaVersion: "21"

      - name: Prepare release artifacts
        uses: strimzi/github-actions/.github/actions/build/release-artifacts@52b17c19f3687e37b47c9c64696b96f28f53625b # v2.3
        with:
          releaseVersion: ${{ inputs.releaseVersion }}
          artifactSuffix: "kafka-kubernetes-config-provider"

      - name: Deploy to Maven Central
        uses: strimzi/github-actions/.github/actions/build/deploy-java@52b17c19f3687e37b47c9c64696b96f28f53625b # v2.3
        with:
          modules: "./"
          gpgPassphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpgSigningKey: ${{ secrets.GPG_SIGNING_KEY }}
          centralUsername: ${{ secrets.CENTRAL_USERNAME }}
          centralPassword: ${{ secrets.CENTRAL_PASSWORD }}





